### ISSUE TITLE
Closing tabs in the tablist should behave just like other Recently Closed Tabs

### ISSUE THREAD

**Issue by whiskytroll** [reblws/tab-search#46]
No big deal, but none the less - when I click the close tab button nothing seems to happen, but if I close the pop up and opens it again the tab is deleted.

I'm on Ff Quantum 58.0.2 (64-bit) branded as Mozilla Firefox for Linux Mint mint-1.0, on a machine with Linux Mint 18.3 Cinnamon.

**Comment by reblws** [comment]
If your "Show Recently Closed" setting is enabled (which it is by default) it should paint the border red to show it's been closed instead of disappearing from the list completely. If you check your tabs at the top, they should be gone. If this is not the case (e.g. the border is red but the tab still exists) try to take a screenshot and let me know.

I realize this might not be the most intuitive behavior, and I'm interested to hear if you have any thoughts about this. I initially wanted to make them disappear immediately regardless of the setting, but wasn't sure how people would react to that.

If "Show Recently Closed" is off, the tabs should disappear from the list instantly.

**Comment by reblws** [comment]
Thanks for your input.

Right now one issue is that once you close them you can't restore them, this isn't ideal behavior as they should technically behave like any other recently closed tabs. For now let's just call a tab deleted from the tab list *Just Closed Tabs* to distinguish them from regular Recently Closed Tabs.

So right now the following should be fixed:
1) A *Just Closed Tab* should be restoreable with a mouse click if it remains in the tab list after being deleted
2) If "Always Show Recently Closed Tabs at the Bottom" is enabled, then *Just Closed Tabs* in the list should move to the bottom of the list after being closed
3) A *Just Closed Tab* should obey the color scheme set by the user.

Can you let me know if there's anything else wrong? I really appreciate these reports, thank you so much. I can't believe I never noticed (3).
